name: Build and publish

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: sabnzbd-sanitizer

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: DockerHub login
        uses: docker/login-action@c144859092e8e353f3e118b0b329679a62351c3e  # v4.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub Container Registry login
        uses: docker/login-action@c144859092e8e353f3e118b0b329679a62351c3e  # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Forgejo Container Registry login
        uses: docker/login-action@c144859092e8e353f3e118b0b329679a62351c3e  # v4.0.0
        with:
          registry: forgejo.treyturner.info
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@eb6512707bea5740b2608f2a43ece7bc543cb75b  # v7.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }}
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }}
            forgejo.treyturner.info/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:latest
            forgejo.treyturner.info/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }}
